### ISSUE TITLE
Mistake in method addMailListsMembers

### ISSUE THREAD

**Issue by kulakowka** [gpit2286/mailgun-es6#10]
@gpit2286 in [docs you write](https://github.com/gpit2286/mailgun-es6#add-mailing-list-members--post-listsaddressmembers): 
> This function will create a new mailing list member. **Member object can be an object or an array of objects**.

But when i try add one member to list 
```javascript
let memberObject = {
  address: 'kulakowka@gmail.com',
  name: 'kulakowka'
}
mailGun.addMailListsMembers('digest@mg.libtuts.com', memberObject, 'yes')
.then(res => console.log(res))
.catch(err => console.log(err))
```

I get error: 
```javascript
{ message: '\'members\' parameter is not a valid JSON list' }
```

When i change `memberObject` to array, it works!

```javascript
mailGun.addMailListsMembers('digest@mg.libtuts.com', [memberObject], 'yes')
```

Is this a bug in documentation or in code?

**Comment by gpit2286** [comment]
So this is what is happening.  In the docs, below the call it talks about what the member objects should be. If you pass a single one of those or an array of those, everything should work fine. 
https://github.com/gpit2286/mailgun-es6#add-mailing-list-members--post-listsaddressmembers 

By adding the email address in an array, as you did, you're using it in an "off label" kind of way. You can see the actual API call on this page: https://documentation.mailgun.com/api-mailinglists.html#mailing-lists under `POST /lists/<address>/members.json`

There are two different ways to add members to a mailing list using the mailgun API.  I choose this one as it was more flexible and easier to add all the information at once.  It would be possible, perhaps, to update the code here: https://github.com/gpit2286/mailgun-es6/blob/34ec3b9855148e5cd77bf0a44dff1cb1fd0034c1/index.js#L1107 to turn 'memberObject' into an array and then the "off label" way would also work.  I believe.

**Comment by kulakowka** [comment]
Thank you. I'm understand.

**Comment by fennellgb23** [comment]
I'm confused on your response some, I believe I'm following this exactly as stated, but I'm getting the error the OP had.

`
var objVars = {
  username: pageData.user.username,
  address: pageData.user.address,
  gender: pageData.user.gender,
  birthday: pageData.user.birthday,
  url: pageData.user.url
  };
	
var memberObject = {
  address: pageData.user.email,
  name: pageData.user.name,
  subscribed: 'yes',
  vars: objVars
};

mailGun.addMailListsMembers(gslist, memberObject, 'yes')
  .then(function(res){
    console.log(res);
    callback(null,'complete');
  })
  .catch(err => console.log(err));
`

and I get error
`{ message: '\'members\' parameter is not a valid JSON list' }`
