### ISSUE TITLE
How to send X-Mailgun-Campaign-Id in header?

### ISSUE THREAD

**Issue by sutkovoy** [gpit2286/mailgun-es6#13]
So my config is:

```
  mailGun.sendEmail({
    to: 'nick@nick.com',
    from: 'from@email.com',
    subject: 'Email Subject',
   html: data.html,
    text: 'Email Text',
    h: 'X-Mailgun-Campaign-Id'
  });
```

But i don't understand how to set value to X-Mailgun-Campaign-Id. Like in http://stackoverflow.com/questions/35526197/how-to-set-x-mailgun-campaign-id-header-in-mailgun-php-api

**Comment by gpit2286** [comment]
You are able to set the campaign with the `o:campaign` 

```javascript 
mailGun.sendEmail({
  to: 'nick@nick.com',
  from: 'from@email.com',
  subject: 'Email Subject',
  html: data.html,
  text: 'Email Text',
  'o:campaign': 'My ID Here' 
});
```

Please close if this fixes your issue or I will close in a week.
