### ISSUE TITLE
undefined issue...

### ISSUE THREAD

**Issue by mogmios** [gpit2286/mailgun-es6#6]
line 114 works better like this.. keeps it from having an error about formData[key] being undefined..

 if (Object.hasOwnProperty(formData[key],'fType')) {

**Comment by gpit2286** [comment]
I don't ever seeing this being a problem as it is looping 

    //Line 103
    for (var key in formData) {
        ...
    }

Correct? Also, I believe you're missing a .call in that chain ;-)
