### ISSUE TITLE
How to validate requests to webhooks?

### ISSUE THREAD

**Issue by m4rcelofs** [gpit2286/mailgun-es6#9]
I was browsing the code for some way to verify that webhook calls came from Mailgun (such as [this function](https://github.com/1lobby/mailgun-js#webhook-validation) on mailgun-js) but couldn't find any.

Is there a function for that?

**Comment by gpit2286** [comment]
It does not currently.  If I have time this weekend I may go back and do a little more developing on this library.  

If you are interested in making it happen, it should be really easy to add this check somewhere around here: https://github.com/gpit2286/mailgun-es6/blob/master/index.js#L178

**Comment by gpit2286** [comment]
Fixed in 808f391
